import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Keycloak KDIPA Theme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3>
          Page examples
        </h3>
    
        <h4>
          Keycloak customization {process.env.NEXT_PUBLIC_CAMUNDA_URL}
        </h4>

        <ul>
          <li><Link href="/keycloak_customization/login">Login</Link></li>
          <li><Link href="/keycloak_customization/registration">Registration</Link></li>
          <li><Link href="/keycloak_customization/verifyEmail">Verify email</Link></li>
          <li><Link href="/keycloak_customization/forgotPassword">Forgot password</Link></li>
          <li><Link href="/keycloak_customization/expirablePageExpired">Page expired</Link></li>
          <li><Link href="/keycloak_customization/error">Error</Link></li>
        </ul>
      </main>
      <footer className={styles.footer}>
        Powered by{' '}Flexy
      </footer>
    </div>
  )
}

export default Home
