import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Keycloak KDIPA Theme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3>
          Landing Pages
        </h3>

        <ul>
          <li><Link href="/landing_page/registration">Landing registration</Link></li>
        </ul>
      </main>
      <footer className={styles.footer}>
        Powered by{' '}Flexy
      </footer>
    </div>
  )
}

export default Home
