import type { NextPage } from 'next'
import { Session } from 'next-auth'
import { getSession, useSession } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import {signIn, useAfterLogout} from "../../src/keycloak/client/authUtils"

async function fetchSomeData() {
  try {
    const data = await getSession()
    let res = await fetch(
      process.env.NEXT_PUBLIC_CAMUNDA_URL+"/engine-rest/user",
      {
        headers: {
          'Authorization': "Bearer "+data!.accessToken
        }
      }
    )
    if ( res.status!=200 ) return JSON.stringify(res.status)

    return JSON.stringify(await res.json(), null, 2)
  } catch(e) {
    console.log("error", e)
    return "error"
  }
}

const Home: NextPage = () => {
  let { data } = useSession()
  const [ res, setRes ] = useState("")
  const {isLoggedOut, loggedOutTip} = useAfterLogout()
  if ( isLoggedOut ) data = null
  console.log({token: (data?.accessToken as string), re: 1})
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
          <button onClick={()=>getSession()}>Refetch session</button>
          {
            loggedOutTip
            ? <div>Just logged out</div>
            : null
          }
          <div>
            <button onClick={()=>signIn()}>sign in</button>
          </div>
          <div>
            <a href="/api/auth/logout">sign out</a>
          </div>
          Access: 
          <pre>{JSON.stringify(data?.user, null, 4)}</pre>
        </>
        {data ? <button onClick={async ()=>setRes(await fetchSomeData())}>Make a request</button> : null }
        {
          res 
          ? <div>
            Retrieved: 
              <pre>{res}</pre>
          </div>
          : null
        }
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
